apiVersion: apps/v1
kind: Deployment
metadata:
  name: password-api
  labels:
    app: password-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: password-api
  template:
    metadata:
      labels:
        app: password-api
    spec:
      containers:
      - name: password-api
        image: nicopaez/password-api
        ports:
        - containerPort: 8080
        envFrom:
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 20        
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 20