apiVersion: v1
kind: Service
metadata:
  name: pingapp-svc
  labels:
    app: password-api
  annotations:
    dev.okteto.com/auto-ingress: "true"    
spec:
  selector:
    app: password-api
  type: NodePort
  ports:
    - port: 8080
      name: http
      targetPort: 8080
      protocol: TCP